mz07:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  mz07_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6

    # gains: # Required because we're controlling an effort interface
    #   J1: {p: 100, i: 10, d: 5.0, i_clamp: 100}
    #   J2: {p: 1000, i: 500, d: 100.0, i_clamp: 100}
    #   J3: {p: 100, i: 10, d: 0.0, i_clamp: 100}
    #   J4: {p: 100, i: 10, d: 0.0, i_clamp: 100}
    #   J5: {p: 10, i: 1, d: 0.0, i_clamp: 100}
    #   J6: {p: 10, i: 1, d: 0.0, i_clamp: 100}